language: python
python:
  - "3.4"
  - "3.6"
  - "nightly"
install:
  - pip install flake8
  - pip install mccabe
  - pip install -r requirements.txt
script:
  - flake8 --max-complexity 10 . --ignore=E501,E402
cache: pip
