language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - flake8 . --ignore=E402,E501,E722
  - BRANCH=$(git rev-parse --abbrev-ref HEAD)

after_success:
  - bash ./travis/trigger_docker_build.sh
cache: pip